---
galaxy_info:
  role_name: ludus_splunk_uf
  author: enonethreezed
  description: Install Splunk Universal Forwarder on Windows and Linux
  license: MIT
  min_ansible_version: "2.9"
dependencies: []
