---
galaxy_info:
  role_name: ludus_gitlab_ldap
  author: enonethreezed
  description: Configure GitLab CE to authenticate against Active Directory via LDAP
  license: MIT
  min_ansible_version: "2.9"
dependencies: []
