---
- name: (SSSD) Install required packages
  ansible.builtin.apt:
    name:
      - sssd
      - sssd-ad
      - realmd
      - adcli
      - krb5-user
      - packagekit
      - samba-common-bin
      - oddjob
      - oddjob-mkhomedir
    state: present
    update_cache: true

- name: (SSSD) Check joined realms
  ansible.builtin.command: realm list
  register: realm_list
  changed_when: false

- name: (SSSD) Join primary domain
  ansible.builtin.expect:
    command: >
      realm join
      --user={{ ludus_sssd_bind_user }}
      {% if ludus_sssd_ou %}--computer-ou="{{ ludus_sssd_ou }}"{% endif %}
      {{ ludus_sssd_domain }}
    responses:
      Password.*: "{{ ludus_sssd_bind_password }}"
    timeout: 60
  when: ludus_sssd_domain not in realm_list.stdout

- name: (SSSD) Join extra domains
  ansible.builtin.expect:
    command: >
      realm join
      --user={{ item.bind_user }}
      {{ item.domain }}
    responses:
      Password.*: "{{ item.bind_password }}"
    timeout: 60
  loop: "{{ ludus_sssd_extra_domains }}"
  when: item.domain not in realm_list.stdout

- name: (SSSD) Deploy sssd.conf
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: '0600'
  notify: Restart SSSD

- name: (SSSD) Enable automatic home directory creation
  ansible.builtin.command: pam-auth-update --enable mkhomedir
  changed_when: true

- name: (SSSD) Restrict SSH access to specific AD users
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} SSSD AD SSH USERS"
    block: |
      AllowUsers {{ ludus_sssd_ssh_users }}
  when: ludus_sssd_ssh_users | length > 0
  notify: Restart SSH

- name: (SSSD) Start and enable SSSD
  ansible.builtin.service:
    name: sssd
    state: started
    enabled: true

handlers:
  - name: Restart SSSD
    ansible.builtin.service:
      name: sssd
      state: restarted

  - name: Restart SSH
    ansible.builtin.service:
      name: ssh
      state: restarted
