---
- name: restart wazuh agent windows
  ansible.windows.win_service:
    name: WazuhSvc
    state: restarted

- name: restart wazuh agent linux
  ansible.builtin.service:
    name: wazuh-agent
    state: restarted
