---
thruntops_ad_kerberoasting_enabled: false

thruntops_ad_kerberoasting_username: svc.backup
thruntops_ad_kerberoasting_password: "password1"
thruntops_ad_kerberoasting_description: >-
  Backup agent service account. Temporary password:
  {{ thruntops_ad_kerberoasting_password }}
thruntops_ad_kerberoasting_spn:
  - backupagent/win11-22h2-1.thruntops.domain
thruntops_ad_kerberoasting_domain_netbios: THRUNTOPS
