---
- name: (GITLAB-LDAP) Append LDAP config to gitlab.rb
  ansible.builtin.blockinfile:
    path: /etc/gitlab/gitlab.rb
    marker: "# {mark} LDAP CONFIGURATION"
    block: "{{ lookup('template', 'gitlab_ldap.rb.j2') }}"

- name: (GITLAB-LDAP) Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure
