---
galaxy_info:
  role_name: ludus_wazuh_agent
  author: thruntops
  description: Install and register Wazuh agent on Windows and Linux hosts
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
    - name: Windows
      versions:
        - 2022Server
        - 11
dependencies: []
