---
- name: (ops) Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: (ops) Add Docker GPG key
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc

- name: (ops) Add Docker apt repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: (ops) Install Docker Engine and Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: (ops) Enable and start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: (ops) Ensure localuser SSH authorized_keys is present
  ansible.posix.authorized_key:
    user: localuser
    state: present
    key: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDyKEgYqyYY5XkbJSZs+zOlZgB61vxFydrfLkywLuRPk qubth@ludus
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2eyuvCcF8X4758t1w402wLXzXCqtlqSOUYMUWhqLbgAOkcg1O1nAq9qc5l22CYOXZCatFCK4yRC+dd4Ef5Y2pb75tse/LHQcug6DAuUr80ch3KgP+zID5wTCaDbTAcrbI6fEbQv8/7zbJNHhZ/FKw0n7dWgoFkx+GPrYkCa7Zra49t1oiO69Vej3sExSoO/cL1RGYiEqB3NP9Z+BSEFh4mBfWzefJIPLXB229w6o/ambjswzg5s45a5kjfZvX+1MdJhkdrF1Ho0NYXZH2fthcrw2lHuNzji8Owj3ingotdxc94iGjQVxWV4MYyxUJX+NPAdyPXOqJ7IdULceHlcdyU2ObzDaTJ5fcYsj4NEEFFKpr4H07BWa7Oj9SRHh7SmD+vNEp4+gIhrStc7jY0X5iYXOHxAIZtJjrAh/wcoMd4Jg409rl0g4myApb8nmUMX/+0nUWExRPzAwhnFrf9kA8SiPZ4mNPmi8N2kxgtR9KGluYK0K2fRuQqmlpIQBjYa8= qubth@ludus

- name: (ops) Deploy Guacamole
  ansible.builtin.include_tasks: guacamole.yml

- name: (ops) Deploy Infection Monkey
  ansible.builtin.include_tasks: monkey.yml
